//ESTE ES UN PROGRAMA QUE CALCULA LA TEMPERATURA EN UNA PLACA, DADAS LAS TEMPERATURAS LATERALES INICIALES EN UN ARCHIVO, LLAMADO DESDE OTRA FUNCION, HECHO POR BRANDON EMMANUEL HERNANDEZ CORONA
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <math.h>
float enter();

int main()//FUNCION PRINCIPAL
{
    enter();//SE LLAMA A LA SEGUNDA FUNCION
    return 0;
}
